name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          path: source

      - name: Checkout destination repo
        uses: actions/checkout@v2
        with:
          repository: yamatoya/yamatoya.github.io
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: dest

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd source
          npm ci

      - name: Build
        run: |
          cd source
          npm run build

      - name: Copy build files
        run: |
          rm -rf dest/*
          cp -r source/dist/* dest/

      - name: Commit and push
        run: |
          cd dest
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deploy from sb1-bnykmy"
          git push