name: Deploy to yamatoya.github.io

on:
  push:
    branches:
      - main  # mainブランチが更新されたときに実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout Source Repository
        uses: actions/checkout@v3

      # yamatoya.github.ioリポジトリをクローン
      - name: Clone yamatoya.github.io Repository
        run: |
          git clone https://${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/yamatoya/yamatoya.github.io.git deploy-repo

      # publicフォルダーの内容をコピー
      - name: Copy files to deploy-repo
        run: |
          rm -rf deploy-repo/*
          cp -r public/* deploy-repo/

      # GitHubリポジトリへのコミットとプッシュ
      - name: Commit and Push Changes
        working-directory: deploy-repo
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Deploy from source repository" || echo "No changes to commit"
          git push origin main
