name: Deploy to yamatoya.github.io

on:
  push:
    branches:
      - main  # mainブランチが更新されたときに実行

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # 環境を指定

    steps:
      # リポジトリをチェックアウト
      - name: Checkout Source Repository
        uses: actions/checkout@v3

      # yamatoya.github.ioリポジトリをクローン
      - name: Clone yamatoya.github.io Repository
        run: |
          git clone https://${{ secrets.DEPLOY_TOKEN }}@github.com/yamatoya/yamatoya.github.io.git deploy-repo

      # publicフォルダーの内容をコピー
      - name: Copy files to deploy-repo
        run: |
          rm -rf deploy-repo/*
          cp -r [!deploy-repo]* deploy-repo/

      # GitHubリポジトリへのコミットとプッシュ
      - name: Commit and Push Changes
        working-directory: deploy-repo
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Deploy from source repository" || echo "No changes to commit"
          git push origin main
